version: '3.8'
services:
  bot:
    image: ghcr.io/eesoymilk/soybot:main
    depends_on:
      db:
        condition: service_healthy
    # volumes:
    #   - $HOME/.config/gcloud/application_default_credentials.json:/gcp/creds.json
    environment:
      TOKEN: ${TOKEN}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      POSTGRES_HOST: db
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # GOOGLE_APPLICATION_CREDENTIALS: /gcp/creds.json
      # GCPLOGS_AUTH_PATH: /gcp/creds.json
    logging:
      driver: gcplogs
      options:
        gcp-project: ${GCP_PROJECT}

  db:
    image: postgres:15.2
    restart: always
    user: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - soybot-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  soybot-data:
