name: deploy-to-kamatera-server
run-name: ${{ github.actor }} is pushing to Kamatera
on:
  push:
    paths:
      - ".github/workflows/main.yml"
      - "Dockerfile"
      - "**.py"
      - "requirements.txt"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  CONTAINER_NAME: soybot-container

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH to Kamatera and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.KAMATERA_HOST }}
          username: root
          password: ${{ secrets.KAMATERA_PASSWORD }}
          script: |
            docker rmi -f ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main || true
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main
            docker stop ${{ env.CONTAINER_NAME }} || true
            docker rm ${{ env.CONTAINER_NAME }} || true
            docker run -d \
              --log-driver=gcplogs
              --env GOOGLE_APPLICATION_CREDENTIALS=/etc/docker/service-account-key.json \
              --name ${{ env.CONTAINER_NAME }} \
              --env TOKEN=${{ secrets.TOKEN }} \
              ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main
