name: deploy-to-kamatera-server
run-name: ${{ github.actor }} is pushing to Kamatera
on:
  push:
    paths:
      - ".github/workflows/main.yml"
      - "Dockerfile"
      - "**.py"
      - "requirements.txt"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  # CONTAINER_NAME: soybot-container

  KAMATERA_USER: soymilk
  KAMATERA_PORT: 22

  POSTGRES_PORT: 5432
  POSTGRES_USER: postgres
  POSTGRES_DB: soybot
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

  GCPLOGS_AUTH_PATH: /root/.config/gcplogs/auth.json
  GCP_PROJECT: eesoybot

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ github.actor }}/soybot-app

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Copy docker-compose.yml to Kamatera
        run: |
          echo "${{ secrets.KAMATERA_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          scp -v -o StrictHostKeyChecking=no \
          -i private_key.pem \
          -P ${{ env.KAMATERA_PORT }} \
          ./docker-compose.yml \
          ${{ env.KAMATERA_USER }}@${{ secrets.KAMATERA_HOST }}:~/app/soybot

      - name: SSH to Kamatera and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.KAMATERA_HOST }}
          username: soymilk
          key: ${{ secrets.KAMATERA_KEY }}
          script: |
            cd ~/app/soybot

            export DISCORD_TOKEN=${{ secrets.TOKEN }}
            export POSTGRES_PORT=${{ env.POSTGRES_PORT }}
            export POSTGRES_USER=${{ env.POSTGRES_USER }}
            export POSTGRES_DB=${{ env.POSTGRES_DB }}
            export POSTGRES_PASSWORD=${{ env.POSTGRES_PASSWORD }}

            sudo docker compose down
            sudo docker system prune -f
            sudo docker compose pull
            sudo docker compose up -d
